version: 2

updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: monthly
    labels:
      - dependencies
      - npm
    groups:
      deps:
        applies-to: version-updates
        dependency-type: production
      deps-dev:
        dependency-type: development
      security:
        applies-to: security-updates
        dependency-type: production
    commit-message:
      prefix: build
      prefix-development: build
      include: scope
