#!/usr/bin/env sh

INCLUDE_PATHS=".bin .husky"
EXCLUDE_PATHS="node_modules"

exit=0
git_files=$(git ls-files --others --exclude-standard --cached)

for path in $INCLUDE_PATHS; do
  sh_files=$(echo "$git_files" | grep -E "$path" | grep -v "$EXCLUDE_PATHS" | tr "\n" " ")
  
  for file in $sh_files; do
    ! shellcheck "$file" && exit=1
  done
done

exit "$exit"
