name: Validate Commits

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    env:
      SHELLCHECKJS_LOGGER_LEVEL: warn
      TURBO_TELEMETRY_DISABLED: true
      TURBO_UI: false
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Add `node_modules` binaries to `PATH`
        run: echo ./node_modules/.bin >> $GITHUB_PATH
      - name: Run commitlint on push
        if: github.event_name == 'push' && !github.event.forced && github.event.before != 0000000000000000000000000000000000000000
        run: commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
      - name: Run commitlint on forced push
        if: github.event_name == 'push' && github.event.forced
        run: commitlint --last --verbose
      - name: Run commitlint on pull request
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Run checks
        run: pnpm run check
